package org.martinmeer.utils;

public enum ParamNames {
    PITCHES,
    DEVIATIONS,
    TOLERANCES_d,
    PITCH_DIAM_TOLERANCE,
    MAJOR_DIAM_TOLERANCE,
    PITCH,
    MULTISTART_TREAD,
    TOLERANCE_ZONE,
    DEVIATION,
    DIRECTION,
    NOMINAL_SIZE,
    PITCH_DIAMETER,
    MAJOR_DIAMETER;


}
